export const CASE_SERVICE_ENDPOINT = process.env.CASE_SERVICE_ENDPOINT;
export const PERSON_SERVICE_ENDPOINT = process.env.PERSON_SERVICE_ENDPOINT;

export const API_PREFIX = "/api/v1";

const CASE_SERVICE_ENDPOINT_WITH_PREFIX = `${CASE_SERVICE_ENDPOINT}${API_PREFIX}`;

export const UM_USER_API = `${CASE_SERVICE_ENDPOINT_WITH_PREFIX}/um/users`;
export const STATIC_DATA_LIST_API = `${CASE_SERVICE_ENDPOINT_WITH_PREFIX}/static-data/lists`;
export const CASE_DETAILS_API = `${CASE_SERVICE_ENDPOINT_WITH_PREFIX}/case-details`;
export const CASE_DETAILS_CLIENTS_API = `${CASE_SERVICE_ENDPOINT_WITH_PREFIX}/case-details/{1}/clients`;
export const PERSONS_API = `${CASE_SERVICE_ENDPOINT_WITH_PREFIX}/persons`;
