/* eslint-disable no-unused-vars  */

export enum CaseTitles {
  CREATE_NEW_CASE = "Create new case",
  MENU_ENQUIRY = "Enquiry",
  MENU_CASE_DETAILS = "Case detail",
  MENU_CLIENT = "Client",
  MENU_CASE_NOTES = "Case note",
  MENU_ASSESSMENT = "Assessment",
  MENU_COURT_MATTERS = "Court matter",
  MENU_REVIEW = "Review",
  MENU_PERSONNEL = "Personnel",
  MENU_ACTIVITY = "Activity",
  MENU_DOCUMENTS = "Document",
  CARD_INTAKE_CASE = "Intake",
  CARD_ENQUIRY_DETAILS = "Enquiry details",
  CARD_ENQUIRER_DETAILS = "Enquirer details",
  CARD_AGENCIES_INVOLVED = "Other agencies involved",
  NOTIFICATION_CASE_CREATED = "Case created successfully.",
  NOTIFICATION_ADD_CLIENT_SUCCESS = "Client successfully added to case.",
  ASSESSMENT_CAPF = "CAPF",
  ASSESSMENT_GENOGRAM = "Genogram",
  ASSESSMENT_CULTURAL_CONSIDERATIONS = "Cultural consideration",
  ASSESSMENT_HARM = "Harm",
  ASSESSMENT_PROTECTION_AND_BELONGING = "Protection and belonging",
  ASSESSMENT_COMPLICATING_FACTORS = "Complicating factors",
  ASSESSMENT_STRENGTHS_AND_RESOURCES = "Strengths and resources",
  ASSESSMENT_SAFETY_SCALE = "Safety scale",
  ASSESSMENT_WORRY_STATEMENTS = "Worry statements",
  ASSESSMENT_GOAL_STATEMENTS = "Goal statements",
  ASSESSMENT_SAFETY_PLAN = "Safety plan",
  ASSESSMENT_NEXT_STEPS = "Next steps",
  ADD_CLIENT = "Add client"
}
